package moldsim.controller;

import java.util.ArrayList;
import java.util.List;
import moldsim.model.RecommendationEngine;
import moldsim.model.SensorEvent;

/**
 * Controller responsible for managing alerts generated by sensors.
 * <p>
 * This class stores event history, logs alerts, and forwards data to a
 * recommendation engine in order to generate appropriate actions.
 */
public class AlertController {

    /**
     * History of processed sensor events.
     */
    private final List<SensorEvent> history;
    /**
     * Recommendation engine used to analyze events.
     */
    private RecommendationEngine recommendationEngine;
    /**
     * Logger used to record alerts and recommendations.
     */
    private AlertLogger logger;
    
    /**
     * Name of the context associated with alerts.
     */
    private String contextName = "Current wall";

    /**
     * Sets the context name used in alert messages.
     *
     * @param contextName the context name to use
     */
    public void setContextName(String contextName) {
        if (contextName == null || contextName.trim().isEmpty()) {
            this.contextName = "Current wall";
        } else {
            this.contextName = contextName.trim();
        }
    }

    /**
     * Creates an alert controller with an empty history.
     */
    public AlertController() {
        this.history = new ArrayList<>();
    }

    /**
     * Assigns a recommendation engine to this controller.
     *
     * @param engine the recommendation engine to use
     */
    public void setRecommendationEngine(RecommendationEngine engine) {
        this.recommendationEngine = engine;
    }

    /**
     * Processes a sensor event.
     * The event is stored, logged, and then analyzed.
     *
     * @param event the event to process
     */
    public void handle(SensorEvent event) {
        history.add(event);
        log(event);
        if (recommendationEngine != null) {
            recommendationEngine.analyze(event).forEach(r -> {
                if (logger != null) {
                    logger.log("[RECOMMENDATION] " + r);
                }
            });
        }
    }

    /**
     * Logs an event according to its type.
     *
     * @param event the event to log
     */
    private void log(SensorEvent event) {
    if (logger == null) return;
    switch (event.getType()) {
        case GLOBAL ->
            logger.log(String.format("[GLOBAL ALERT] %s | Week %d | %s | rate %.1f%%",
                contextName, event.getWeek(), event.getAlertLevel(), event.getMoldRate() * 100));
        case SHELF -> {
            if (event.getShelf() == null) {
                logger.log(String.format("[ERROR] %s | Week %d | SHELF event without shelf",
                    contextName, event.getWeek()));
                return;
            }
            logger.log(String.format("[SHELF ALERT] %s | Week %d | %s | shelf %s | rate %.1f%%",
                contextName, event.getWeek(), event.getAlertLevel(),
                event.getShelf().getId(), event.getMoldRate() * 100));
        }
    }
}

    /**
     * Sets the logger used by this controller.
     *
     * @param logger the logger to use
     */
    public void setLogger(AlertLogger logger) {
        this.logger = logger;
    }

    /**
     * Removes all events from the history.
     */
    public void clearHistory() {
        history.clear();
    }

    /**
     * Returns the history of processed events.
     *
     * @return the list of recorded events
     */
    public List<SensorEvent> getHistory() {
        return history;
    }

    /**
     * Returns the associated recommendation engine.
     *
     * @return the recommendation engine, or null if none is configured
     */
    public RecommendationEngine getRecommendationEngine() {
        return recommendationEngine;
    }
}