package moldsim.model;

/**
 * Represents an event generated by a mold sensor during the simulation.
 * <p>
 * A sensor event contains information about the simulation week, alert level,
 * measured mold rate, affected wall, event type, and optionally a shelf.
 */
public class SensorEvent {

    /** Simulation week when the event occurred. */
    private final int week;
    /** Severity level of the alert. */
    private final AlertLevel alertLevel;
    /** Measured mold rate associated with the event. */
    private final double moldRate;
    /** Wall affected by the event. */
    private final Wall wall;
    /** Type of event (GLOBAL or SHELF). */
    private final EventType type;
    /** Optional shelf affected by the event (null for global events). */
    private final Shelf shelf;

    /**
     * Creates a sensor event with all attributes.
     *
     * @param week simulation week
     * @param alertLevel alert severity level
     * @param moldRate measured mold rate
     * @param wall affected wall
     * @param type event type
     * @param shelf affected shelf (null if global event)
     */
    public SensorEvent(int week, AlertLevel alertLevel, double moldRate, Wall wall, EventType type, Shelf shelf) {
        this.week       = week;
        this.alertLevel = alertLevel;
        this.moldRate   = moldRate;
        this.wall       = wall;
        this.type       = type;
        this.shelf      = shelf;
    }

    /**
     * Creates a global sensor event (no shelf involved).
     *
     * @param week simulation week
     * @param alertLevel alert severity level
     * @param moldRate measured mold rate
     * @param wall affected wall
     */
    public SensorEvent(int week, AlertLevel alertLevel, double moldRate, Wall wall) {
        this(week, alertLevel, moldRate, wall, EventType.GLOBAL, null);
    }

    /**
     * Returns the simulation week of the event.
     *
     * @return simulation week
     */
    public int getWeek(){ 
        return week;
    }

    /**
     * Returns the alert level of the event.
     *
     * @return alert level
     */
    public AlertLevel getAlertLevel(){
        return alertLevel;
    }

    /**
     * Returns the mold rate of the event.
     *
     * @return mold rate
     */
    public double getMoldRate(){
        return moldRate;
    }

    /**
     * Returns the affected wall.
     *
     * @return wall
     */
    public Wall getWall(){
        return wall;
    }

    /**
     * Returns the event type.
     *
     * @return event type
     */
    public EventType getType(){
        return type;
    }

    /**
     * Returns the affected shelf (may be null for global events).
     *
     * @return shelf or null
     */
    public Shelf getShelf(){
        return shelf;
    }

}